// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BattleRallyArea.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from BattleRallyArea.proto</summary>
  public static partial class BattleRallyAreaReflection {

    #region Descriptor
    /// <summary>File descriptor for BattleRallyArea.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleRallyAreaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVCYXR0bGVSYWxseUFyZWEucHJvdG8SDFJlTWFzdGVyc0xpYiKpAQoPQmF0",
            "dGxlUmFsbHlBcmVhEhwKFGJhdHRsZV9yYWxseV9hcmVhX2lkGAEgASgEEg0K",
            "BWZsb29yGAIgASgDEhIKCmRpZmZpY3VsdHkYAyABKAMSIwobbXVsdGlwbGVf",
            "cGFyYW1ldGVyX2Jvb3N0X2lkGAQgASgEEhgKEHJhbGx5X3BvaW50c19xdHkY",
            "BSABKAMSCgoCdTIYBiABKAMSCgoCdTMYByABKAMiRgoUQmF0dGxlUmFsbHlB",
            "cmVhVGFibGUSLgoHZW50cmllcxgBIAMoCzIdLlJlTWFzdGVyc0xpYi5CYXR0",
            "bGVSYWxseUFyZWFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.BattleRallyArea), global::ReMastersLib.BattleRallyArea.Parser, new[]{ "BattleRallyAreaId", "Floor", "Difficulty", "MultipleParameterBoostId", "RallyPointsQty", "U2", "U3" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.BattleRallyAreaTable), global::ReMastersLib.BattleRallyAreaTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BattleRallyArea : pb::IMessage<BattleRallyArea>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattleRallyArea> _parser = new pb::MessageParser<BattleRallyArea>(() => new BattleRallyArea());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattleRallyArea> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.BattleRallyAreaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyArea() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyArea(BattleRallyArea other) : this() {
      battleRallyAreaId_ = other.battleRallyAreaId_;
      floor_ = other.floor_;
      difficulty_ = other.difficulty_;
      multipleParameterBoostId_ = other.multipleParameterBoostId_;
      rallyPointsQty_ = other.rallyPointsQty_;
      u2_ = other.u2_;
      u3_ = other.u3_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyArea Clone() {
      return new BattleRallyArea(this);
    }

    /// <summary>Field number for the "battle_rally_area_id" field.</summary>
    public const int BattleRallyAreaIdFieldNumber = 1;
    private ulong battleRallyAreaId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BattleRallyAreaId {
      get { return battleRallyAreaId_; }
      set {
        battleRallyAreaId_ = value;
      }
    }

    /// <summary>Field number for the "floor" field.</summary>
    public const int FloorFieldNumber = 2;
    private long floor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Floor {
      get { return floor_; }
      set {
        floor_ = value;
      }
    }

    /// <summary>Field number for the "difficulty" field.</summary>
    public const int DifficultyFieldNumber = 3;
    private long difficulty_;
    /// <summary>
    /// 1 = easy, 2 = hard, 3 = very hard, 9 = lucky
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Difficulty {
      get { return difficulty_; }
      set {
        difficulty_ = value;
      }
    }

    /// <summary>Field number for the "multiple_parameter_boost_id" field.</summary>
    public const int MultipleParameterBoostIdFieldNumber = 4;
    private ulong multipleParameterBoostId_;
    /// <summary>
    /// MultipleParameterBoost.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MultipleParameterBoostId {
      get { return multipleParameterBoostId_; }
      set {
        multipleParameterBoostId_ = value;
      }
    }

    /// <summary>Field number for the "rally_points_qty" field.</summary>
    public const int RallyPointsQtyFieldNumber = 5;
    private long rallyPointsQty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long RallyPointsQty {
      get { return rallyPointsQty_; }
      set {
        rallyPointsQty_ = value;
      }
    }

    /// <summary>Field number for the "u2" field.</summary>
    public const int U2FieldNumber = 6;
    private long u2_;
    /// <summary>
    /// BattleRallyId ?
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long U2 {
      get { return u2_; }
      set {
        u2_ = value;
      }
    }

    /// <summary>Field number for the "u3" field.</summary>
    public const int U3FieldNumber = 7;
    private long u3_;
    /// <summary>
    /// BattleRallyId ?
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long U3 {
      get { return u3_; }
      set {
        u3_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattleRallyArea);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattleRallyArea other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleRallyAreaId != other.BattleRallyAreaId) return false;
      if (Floor != other.Floor) return false;
      if (Difficulty != other.Difficulty) return false;
      if (MultipleParameterBoostId != other.MultipleParameterBoostId) return false;
      if (RallyPointsQty != other.RallyPointsQty) return false;
      if (U2 != other.U2) return false;
      if (U3 != other.U3) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleRallyAreaId != 0UL) hash ^= BattleRallyAreaId.GetHashCode();
      if (Floor != 0L) hash ^= Floor.GetHashCode();
      if (Difficulty != 0L) hash ^= Difficulty.GetHashCode();
      if (MultipleParameterBoostId != 0UL) hash ^= MultipleParameterBoostId.GetHashCode();
      if (RallyPointsQty != 0L) hash ^= RallyPointsQty.GetHashCode();
      if (U2 != 0L) hash ^= U2.GetHashCode();
      if (U3 != 0L) hash ^= U3.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BattleRallyAreaId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BattleRallyAreaId);
      }
      if (Floor != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Floor);
      }
      if (Difficulty != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Difficulty);
      }
      if (MultipleParameterBoostId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(MultipleParameterBoostId);
      }
      if (RallyPointsQty != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RallyPointsQty);
      }
      if (U2 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(U2);
      }
      if (U3 != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(U3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BattleRallyAreaId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BattleRallyAreaId);
      }
      if (Floor != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Floor);
      }
      if (Difficulty != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Difficulty);
      }
      if (MultipleParameterBoostId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(MultipleParameterBoostId);
      }
      if (RallyPointsQty != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(RallyPointsQty);
      }
      if (U2 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(U2);
      }
      if (U3 != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(U3);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BattleRallyAreaId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BattleRallyAreaId);
      }
      if (Floor != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Floor);
      }
      if (Difficulty != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Difficulty);
      }
      if (MultipleParameterBoostId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MultipleParameterBoostId);
      }
      if (RallyPointsQty != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(RallyPointsQty);
      }
      if (U2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(U2);
      }
      if (U3 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(U3);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattleRallyArea other) {
      if (other == null) {
        return;
      }
      if (other.BattleRallyAreaId != 0UL) {
        BattleRallyAreaId = other.BattleRallyAreaId;
      }
      if (other.Floor != 0L) {
        Floor = other.Floor;
      }
      if (other.Difficulty != 0L) {
        Difficulty = other.Difficulty;
      }
      if (other.MultipleParameterBoostId != 0UL) {
        MultipleParameterBoostId = other.MultipleParameterBoostId;
      }
      if (other.RallyPointsQty != 0L) {
        RallyPointsQty = other.RallyPointsQty;
      }
      if (other.U2 != 0L) {
        U2 = other.U2;
      }
      if (other.U3 != 0L) {
        U3 = other.U3;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BattleRallyAreaId = input.ReadUInt64();
            break;
          }
          case 16: {
            Floor = input.ReadInt64();
            break;
          }
          case 24: {
            Difficulty = input.ReadInt64();
            break;
          }
          case 32: {
            MultipleParameterBoostId = input.ReadUInt64();
            break;
          }
          case 40: {
            RallyPointsQty = input.ReadInt64();
            break;
          }
          case 48: {
            U2 = input.ReadInt64();
            break;
          }
          case 56: {
            U3 = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BattleRallyAreaId = input.ReadUInt64();
            break;
          }
          case 16: {
            Floor = input.ReadInt64();
            break;
          }
          case 24: {
            Difficulty = input.ReadInt64();
            break;
          }
          case 32: {
            MultipleParameterBoostId = input.ReadUInt64();
            break;
          }
          case 40: {
            RallyPointsQty = input.ReadInt64();
            break;
          }
          case 48: {
            U2 = input.ReadInt64();
            break;
          }
          case 56: {
            U3 = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BattleRallyAreaTable : pb::IMessage<BattleRallyAreaTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattleRallyAreaTable> _parser = new pb::MessageParser<BattleRallyAreaTable>(() => new BattleRallyAreaTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattleRallyAreaTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.BattleRallyAreaReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyAreaTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyAreaTable(BattleRallyAreaTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyAreaTable Clone() {
      return new BattleRallyAreaTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.BattleRallyArea> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.BattleRallyArea.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.BattleRallyArea> entries_ = new pbc::RepeatedField<global::ReMastersLib.BattleRallyArea>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.BattleRallyArea> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattleRallyAreaTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattleRallyAreaTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattleRallyAreaTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
