// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/BattleRallyShop.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/BattleRallyShop.proto</summary>
  public static partial class BattleRallyShopReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/BattleRallyShop.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleRallyShopReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQcm90by9CYXR0bGVSYWxseVNob3AucHJvdG8SDFJlTWFzdGVyc0xpYiKb",
            "AQoPQmF0dGxlUmFsbHlTaG9wEhwKFGJhdHRsZV9yYWxseV9zaG9wX2lkGAEg",
            "ASgDEisKI2JhdHRsZV9yYWxseV9zaG9wX2l0ZW1fY29uZGl0aW9uX2lkGAIg",
            "ASgJEg4KBmZsb29ycxgDIAMoDRIVCg1pdGVtX3Bvc2l0aW9uGAQgASgNEgoK",
            "AnUxGAUgASgDEgoKAnUyGAYgASgDIkYKFEJhdHRsZVJhbGx5U2hvcFRhYmxl",
            "Ei4KB2VudHJpZXMYASADKAsyHS5SZU1hc3RlcnNMaWIuQmF0dGxlUmFsbHlT",
            "aG9wYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.BattleRallyShop), global::ReMastersLib.BattleRallyShop.Parser, new[]{ "BattleRallyShopId", "BattleRallyShopItemConditionId", "Floors", "ItemPosition", "U1", "U2" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.BattleRallyShopTable), global::ReMastersLib.BattleRallyShopTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BattleRallyShop : pb::IMessage<BattleRallyShop>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattleRallyShop> _parser = new pb::MessageParser<BattleRallyShop>(() => new BattleRallyShop());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattleRallyShop> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.BattleRallyShopReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyShop() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyShop(BattleRallyShop other) : this() {
      battleRallyShopId_ = other.battleRallyShopId_;
      battleRallyShopItemConditionId_ = other.battleRallyShopItemConditionId_;
      floors_ = other.floors_.Clone();
      itemPosition_ = other.itemPosition_;
      u1_ = other.u1_;
      u2_ = other.u2_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyShop Clone() {
      return new BattleRallyShop(this);
    }

    /// <summary>Field number for the "battle_rally_shop_id" field.</summary>
    public const int BattleRallyShopIdFieldNumber = 1;
    private long battleRallyShopId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long BattleRallyShopId {
      get { return battleRallyShopId_; }
      set {
        battleRallyShopId_ = value;
      }
    }

    /// <summary>Field number for the "battle_rally_shop_item_condition_id" field.</summary>
    public const int BattleRallyShopItemConditionIdFieldNumber = 2;
    private string battleRallyShopItemConditionId_ = "";
    /// <summary>
    /// BattleRallyShopItemCondition.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BattleRallyShopItemConditionId {
      get { return battleRallyShopItemConditionId_; }
      set {
        battleRallyShopItemConditionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "floors" field.</summary>
    public const int FloorsFieldNumber = 3;
    private static readonly pb::FieldCodec<uint> _repeated_floors_codec
        = pb::FieldCodec.ForUInt32(26);
    private readonly pbc::RepeatedField<uint> floors_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<uint> Floors {
      get { return floors_; }
    }

    /// <summary>Field number for the "item_position" field.</summary>
    public const int ItemPositionFieldNumber = 4;
    private uint itemPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ItemPosition {
      get { return itemPosition_; }
      set {
        itemPosition_ = value;
      }
    }

    /// <summary>Field number for the "u1" field.</summary>
    public const int U1FieldNumber = 5;
    private long u1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long U1 {
      get { return u1_; }
      set {
        u1_ = value;
      }
    }

    /// <summary>Field number for the "u2" field.</summary>
    public const int U2FieldNumber = 6;
    private long u2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long U2 {
      get { return u2_; }
      set {
        u2_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattleRallyShop);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattleRallyShop other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BattleRallyShopId != other.BattleRallyShopId) return false;
      if (BattleRallyShopItemConditionId != other.BattleRallyShopItemConditionId) return false;
      if(!floors_.Equals(other.floors_)) return false;
      if (ItemPosition != other.ItemPosition) return false;
      if (U1 != other.U1) return false;
      if (U2 != other.U2) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BattleRallyShopId != 0L) hash ^= BattleRallyShopId.GetHashCode();
      if (BattleRallyShopItemConditionId.Length != 0) hash ^= BattleRallyShopItemConditionId.GetHashCode();
      hash ^= floors_.GetHashCode();
      if (ItemPosition != 0) hash ^= ItemPosition.GetHashCode();
      if (U1 != 0L) hash ^= U1.GetHashCode();
      if (U2 != 0L) hash ^= U2.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BattleRallyShopId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(BattleRallyShopId);
      }
      if (BattleRallyShopItemConditionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BattleRallyShopItemConditionId);
      }
      floors_.WriteTo(output, _repeated_floors_codec);
      if (ItemPosition != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ItemPosition);
      }
      if (U1 != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(U1);
      }
      if (U2 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(U2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BattleRallyShopId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(BattleRallyShopId);
      }
      if (BattleRallyShopItemConditionId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(BattleRallyShopItemConditionId);
      }
      floors_.WriteTo(ref output, _repeated_floors_codec);
      if (ItemPosition != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(ItemPosition);
      }
      if (U1 != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(U1);
      }
      if (U2 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(U2);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BattleRallyShopId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(BattleRallyShopId);
      }
      if (BattleRallyShopItemConditionId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BattleRallyShopItemConditionId);
      }
      size += floors_.CalculateSize(_repeated_floors_codec);
      if (ItemPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemPosition);
      }
      if (U1 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(U1);
      }
      if (U2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(U2);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattleRallyShop other) {
      if (other == null) {
        return;
      }
      if (other.BattleRallyShopId != 0L) {
        BattleRallyShopId = other.BattleRallyShopId;
      }
      if (other.BattleRallyShopItemConditionId.Length != 0) {
        BattleRallyShopItemConditionId = other.BattleRallyShopItemConditionId;
      }
      floors_.Add(other.floors_);
      if (other.ItemPosition != 0) {
        ItemPosition = other.ItemPosition;
      }
      if (other.U1 != 0L) {
        U1 = other.U1;
      }
      if (other.U2 != 0L) {
        U2 = other.U2;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BattleRallyShopId = input.ReadInt64();
            break;
          }
          case 18: {
            BattleRallyShopItemConditionId = input.ReadString();
            break;
          }
          case 26:
          case 24: {
            floors_.AddEntriesFrom(input, _repeated_floors_codec);
            break;
          }
          case 32: {
            ItemPosition = input.ReadUInt32();
            break;
          }
          case 40: {
            U1 = input.ReadInt64();
            break;
          }
          case 48: {
            U2 = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BattleRallyShopId = input.ReadInt64();
            break;
          }
          case 18: {
            BattleRallyShopItemConditionId = input.ReadString();
            break;
          }
          case 26:
          case 24: {
            floors_.AddEntriesFrom(ref input, _repeated_floors_codec);
            break;
          }
          case 32: {
            ItemPosition = input.ReadUInt32();
            break;
          }
          case 40: {
            U1 = input.ReadInt64();
            break;
          }
          case 48: {
            U2 = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class BattleRallyShopTable : pb::IMessage<BattleRallyShopTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BattleRallyShopTable> _parser = new pb::MessageParser<BattleRallyShopTable>(() => new BattleRallyShopTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BattleRallyShopTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.BattleRallyShopReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyShopTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyShopTable(BattleRallyShopTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BattleRallyShopTable Clone() {
      return new BattleRallyShopTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.BattleRallyShop> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.BattleRallyShop.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.BattleRallyShop> entries_ = new pbc::RepeatedField<global::ReMastersLib.BattleRallyShop>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.BattleRallyShop> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BattleRallyShopTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BattleRallyShopTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BattleRallyShopTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
