// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/ChampionBattleRegion.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/ChampionBattleRegion.proto</summary>
  public static partial class ChampionBattleRegionReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/ChampionBattleRegion.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ChampionBattleRegionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBQcm90by9DaGFtcGlvbkJhdHRsZVJlZ2lvbi5wcm90bxIMUmVNYXN0ZXJz",
            "TGliIo0BChRDaGFtcGlvbkJhdHRsZVJlZ2lvbhIeChZjaGFtcGlvbkJhdHRs",
            "ZVJlZ2lvbklkGAEgASgNEgoKAnUxGAIgASgJEg4KBm5hbWVJZBgDIAEoCRIQ",
            "CghiYW5uZXJJZBgEIAEoDRIKCgJ1MhgFIAEoDRIKCgJ1MxgGIAEoCRIPCgdi",
            "Z21OYW1lGAcgASgJIlAKGUNoYW1waW9uQmF0dGxlUmVnaW9uVGFibGUSMwoH",
            "ZW50cmllcxgBIAMoCzIiLlJlTWFzdGVyc0xpYi5DaGFtcGlvbkJhdHRsZVJl",
            "Z2lvbmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.ChampionBattleRegion), global::ReMastersLib.ChampionBattleRegion.Parser, new[]{ "ChampionBattleRegionId", "U1", "NameId", "BannerId", "U2", "U3", "BgmName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.ChampionBattleRegionTable), global::ReMastersLib.ChampionBattleRegionTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ChampionBattleRegion : pb::IMessage<ChampionBattleRegion>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChampionBattleRegion> _parser = new pb::MessageParser<ChampionBattleRegion>(() => new ChampionBattleRegion());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChampionBattleRegion> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.ChampionBattleRegionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChampionBattleRegion() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChampionBattleRegion(ChampionBattleRegion other) : this() {
      championBattleRegionId_ = other.championBattleRegionId_;
      u1_ = other.u1_;
      nameId_ = other.nameId_;
      bannerId_ = other.bannerId_;
      u2_ = other.u2_;
      u3_ = other.u3_;
      bgmName_ = other.bgmName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChampionBattleRegion Clone() {
      return new ChampionBattleRegion(this);
    }

    /// <summary>Field number for the "championBattleRegionId" field.</summary>
    public const int ChampionBattleRegionIdFieldNumber = 1;
    private uint championBattleRegionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ChampionBattleRegionId {
      get { return championBattleRegionId_; }
      set {
        championBattleRegionId_ = value;
      }
    }

    /// <summary>Field number for the "u1" field.</summary>
    public const int U1FieldNumber = 2;
    private string u1_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string U1 {
      get { return u1_; }
      set {
        u1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nameId" field.</summary>
    public const int NameIdFieldNumber = 3;
    private string nameId_ = "";
    /// <summary>
    /// champion_battle_region_name_xx.lsd
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NameId {
      get { return nameId_; }
      set {
        nameId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bannerId" field.</summary>
    public const int BannerIdFieldNumber = 4;
    private uint bannerId_;
    /// <summary>
    /// Banner.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BannerId {
      get { return bannerId_; }
      set {
        bannerId_ = value;
      }
    }

    /// <summary>Field number for the "u2" field.</summary>
    public const int U2FieldNumber = 5;
    private uint u2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint U2 {
      get { return u2_; }
      set {
        u2_ = value;
      }
    }

    /// <summary>Field number for the "u3" field.</summary>
    public const int U3FieldNumber = 6;
    private string u3_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string U3 {
      get { return u3_; }
      set {
        u3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bgmName" field.</summary>
    public const int BgmNameFieldNumber = 7;
    private string bgmName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string BgmName {
      get { return bgmName_; }
      set {
        bgmName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChampionBattleRegion);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChampionBattleRegion other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChampionBattleRegionId != other.ChampionBattleRegionId) return false;
      if (U1 != other.U1) return false;
      if (NameId != other.NameId) return false;
      if (BannerId != other.BannerId) return false;
      if (U2 != other.U2) return false;
      if (U3 != other.U3) return false;
      if (BgmName != other.BgmName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChampionBattleRegionId != 0) hash ^= ChampionBattleRegionId.GetHashCode();
      if (U1.Length != 0) hash ^= U1.GetHashCode();
      if (NameId.Length != 0) hash ^= NameId.GetHashCode();
      if (BannerId != 0) hash ^= BannerId.GetHashCode();
      if (U2 != 0) hash ^= U2.GetHashCode();
      if (U3.Length != 0) hash ^= U3.GetHashCode();
      if (BgmName.Length != 0) hash ^= BgmName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChampionBattleRegionId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChampionBattleRegionId);
      }
      if (U1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(U1);
      }
      if (NameId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NameId);
      }
      if (BannerId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BannerId);
      }
      if (U2 != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(U2);
      }
      if (U3.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(U3);
      }
      if (BgmName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BgmName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChampionBattleRegionId != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ChampionBattleRegionId);
      }
      if (U1.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(U1);
      }
      if (NameId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(NameId);
      }
      if (BannerId != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(BannerId);
      }
      if (U2 != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(U2);
      }
      if (U3.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(U3);
      }
      if (BgmName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(BgmName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChampionBattleRegionId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ChampionBattleRegionId);
      }
      if (U1.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(U1);
      }
      if (NameId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NameId);
      }
      if (BannerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BannerId);
      }
      if (U2 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(U2);
      }
      if (U3.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(U3);
      }
      if (BgmName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BgmName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChampionBattleRegion other) {
      if (other == null) {
        return;
      }
      if (other.ChampionBattleRegionId != 0) {
        ChampionBattleRegionId = other.ChampionBattleRegionId;
      }
      if (other.U1.Length != 0) {
        U1 = other.U1;
      }
      if (other.NameId.Length != 0) {
        NameId = other.NameId;
      }
      if (other.BannerId != 0) {
        BannerId = other.BannerId;
      }
      if (other.U2 != 0) {
        U2 = other.U2;
      }
      if (other.U3.Length != 0) {
        U3 = other.U3;
      }
      if (other.BgmName.Length != 0) {
        BgmName = other.BgmName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ChampionBattleRegionId = input.ReadUInt32();
            break;
          }
          case 18: {
            U1 = input.ReadString();
            break;
          }
          case 26: {
            NameId = input.ReadString();
            break;
          }
          case 32: {
            BannerId = input.ReadUInt32();
            break;
          }
          case 40: {
            U2 = input.ReadUInt32();
            break;
          }
          case 50: {
            U3 = input.ReadString();
            break;
          }
          case 58: {
            BgmName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ChampionBattleRegionId = input.ReadUInt32();
            break;
          }
          case 18: {
            U1 = input.ReadString();
            break;
          }
          case 26: {
            NameId = input.ReadString();
            break;
          }
          case 32: {
            BannerId = input.ReadUInt32();
            break;
          }
          case 40: {
            U2 = input.ReadUInt32();
            break;
          }
          case 50: {
            U3 = input.ReadString();
            break;
          }
          case 58: {
            BgmName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ChampionBattleRegionTable : pb::IMessage<ChampionBattleRegionTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChampionBattleRegionTable> _parser = new pb::MessageParser<ChampionBattleRegionTable>(() => new ChampionBattleRegionTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChampionBattleRegionTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.ChampionBattleRegionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChampionBattleRegionTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChampionBattleRegionTable(ChampionBattleRegionTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChampionBattleRegionTable Clone() {
      return new ChampionBattleRegionTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.ChampionBattleRegion> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.ChampionBattleRegion.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.ChampionBattleRegion> entries_ = new pbc::RepeatedField<global::ReMastersLib.ChampionBattleRegion>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.ChampionBattleRegion> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChampionBattleRegionTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChampionBattleRegionTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChampionBattleRegionTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
