// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/DamageChallengeQuestSetting.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/DamageChallengeQuestSetting.proto</summary>
  public static partial class DamageChallengeQuestSettingReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/DamageChallengeQuestSetting.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static DamageChallengeQuestSettingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidQcm90by9EYW1hZ2VDaGFsbGVuZ2VRdWVzdFNldHRpbmcucHJvdG8SDFJl",
            "TWFzdGVyc0xpYiK3AQobRGFtYWdlQ2hhbGxlbmdlUXVlc3RTZXR0aW5nEhYK",
            "DnN0b3J5X3F1ZXN0X2lkGAEgASgDEkUKFWRhbWFnZV9jaGFsbGVuZ2VfcnVs",
            "ZRgCIAEoDjImLlJlTWFzdGVyc0xpYi5EYW1hZ2VDaGFsbGVuZ2VUaGVtZVJ1",
            "bGUSFwoPdHJhaW5lcl9iYXNlX2lkGAMgASgDEiAKGGN5Y2xpY19yYW5raW5n",
            "X3F1ZXN0X251bRgEIAEoBSJeCiBEYW1hZ2VDaGFsbGVuZ2VRdWVzdFNldHRp",
            "bmdUYWJsZRI6CgdlbnRyaWVzGAEgAygLMikuUmVNYXN0ZXJzTGliLkRhbWFn",
            "ZUNoYWxsZW5nZVF1ZXN0U2V0dGluZypIChhEYW1hZ2VDaGFsbGVuZ2VUaGVt",
            "ZVJ1bGUSCAoEbm9uZRAAEhAKCV82MDYwXzAwMRDB3fIcEhAKCV82MDYwXzAw",
            "MhDC3fIcYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ReMastersLib.DamageChallengeThemeRule), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.DamageChallengeQuestSetting), global::ReMastersLib.DamageChallengeQuestSetting.Parser, new[]{ "StoryQuestId", "DamageChallengeRule", "TrainerBaseId", "CyclicRankingQuestNum" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.DamageChallengeQuestSettingTable), global::ReMastersLib.DamageChallengeQuestSettingTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DamageChallengeThemeRule {
    [pbr::OriginalName("none")] None = 0,
    [pbr::OriginalName("_6060_001")] _6060001 = 60600001,
    [pbr::OriginalName("_6060_002")] _6060002 = 60600002,
  }

  #endregion

  #region Messages
  public sealed partial class DamageChallengeQuestSetting : pb::IMessage<DamageChallengeQuestSetting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DamageChallengeQuestSetting> _parser = new pb::MessageParser<DamageChallengeQuestSetting>(() => new DamageChallengeQuestSetting());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DamageChallengeQuestSetting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.DamageChallengeQuestSettingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DamageChallengeQuestSetting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DamageChallengeQuestSetting(DamageChallengeQuestSetting other) : this() {
      storyQuestId_ = other.storyQuestId_;
      damageChallengeRule_ = other.damageChallengeRule_;
      trainerBaseId_ = other.trainerBaseId_;
      cyclicRankingQuestNum_ = other.cyclicRankingQuestNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DamageChallengeQuestSetting Clone() {
      return new DamageChallengeQuestSetting(this);
    }

    /// <summary>Field number for the "story_quest_id" field.</summary>
    public const int StoryQuestIdFieldNumber = 1;
    private long storyQuestId_;
    /// <summary>
    /// StoryQuest.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long StoryQuestId {
      get { return storyQuestId_; }
      set {
        storyQuestId_ = value;
      }
    }

    /// <summary>Field number for the "damage_challenge_rule" field.</summary>
    public const int DamageChallengeRuleFieldNumber = 2;
    private global::ReMastersLib.DamageChallengeThemeRule damageChallengeRule_ = global::ReMastersLib.DamageChallengeThemeRule.None;
    /// <summary>
    /// champion_battle_theme_xx.lsd / champion_battle_rule_xx.lsd
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ReMastersLib.DamageChallengeThemeRule DamageChallengeRule {
      get { return damageChallengeRule_; }
      set {
        damageChallengeRule_ = value;
      }
    }

    /// <summary>Field number for the "trainer_base_id" field.</summary>
    public const int TrainerBaseIdFieldNumber = 3;
    private long trainerBaseId_;
    /// <summary>
    /// TrainerBase.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TrainerBaseId {
      get { return trainerBaseId_; }
      set {
        trainerBaseId_ = value;
      }
    }

    /// <summary>Field number for the "cyclic_ranking_quest_num" field.</summary>
    public const int CyclicRankingQuestNumFieldNumber = 4;
    private int cyclicRankingQuestNum_;
    /// <summary>
    /// CyclicRankingQuestGroup.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CyclicRankingQuestNum {
      get { return cyclicRankingQuestNum_; }
      set {
        cyclicRankingQuestNum_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DamageChallengeQuestSetting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DamageChallengeQuestSetting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StoryQuestId != other.StoryQuestId) return false;
      if (DamageChallengeRule != other.DamageChallengeRule) return false;
      if (TrainerBaseId != other.TrainerBaseId) return false;
      if (CyclicRankingQuestNum != other.CyclicRankingQuestNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (StoryQuestId != 0L) hash ^= StoryQuestId.GetHashCode();
      if (DamageChallengeRule != global::ReMastersLib.DamageChallengeThemeRule.None) hash ^= DamageChallengeRule.GetHashCode();
      if (TrainerBaseId != 0L) hash ^= TrainerBaseId.GetHashCode();
      if (CyclicRankingQuestNum != 0) hash ^= CyclicRankingQuestNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (StoryQuestId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StoryQuestId);
      }
      if (DamageChallengeRule != global::ReMastersLib.DamageChallengeThemeRule.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DamageChallengeRule);
      }
      if (TrainerBaseId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TrainerBaseId);
      }
      if (CyclicRankingQuestNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CyclicRankingQuestNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (StoryQuestId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(StoryQuestId);
      }
      if (DamageChallengeRule != global::ReMastersLib.DamageChallengeThemeRule.None) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DamageChallengeRule);
      }
      if (TrainerBaseId != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TrainerBaseId);
      }
      if (CyclicRankingQuestNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CyclicRankingQuestNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (StoryQuestId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(StoryQuestId);
      }
      if (DamageChallengeRule != global::ReMastersLib.DamageChallengeThemeRule.None) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DamageChallengeRule);
      }
      if (TrainerBaseId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TrainerBaseId);
      }
      if (CyclicRankingQuestNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CyclicRankingQuestNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DamageChallengeQuestSetting other) {
      if (other == null) {
        return;
      }
      if (other.StoryQuestId != 0L) {
        StoryQuestId = other.StoryQuestId;
      }
      if (other.DamageChallengeRule != global::ReMastersLib.DamageChallengeThemeRule.None) {
        DamageChallengeRule = other.DamageChallengeRule;
      }
      if (other.TrainerBaseId != 0L) {
        TrainerBaseId = other.TrainerBaseId;
      }
      if (other.CyclicRankingQuestNum != 0) {
        CyclicRankingQuestNum = other.CyclicRankingQuestNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StoryQuestId = input.ReadInt64();
            break;
          }
          case 16: {
            DamageChallengeRule = (global::ReMastersLib.DamageChallengeThemeRule) input.ReadEnum();
            break;
          }
          case 24: {
            TrainerBaseId = input.ReadInt64();
            break;
          }
          case 32: {
            CyclicRankingQuestNum = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            StoryQuestId = input.ReadInt64();
            break;
          }
          case 16: {
            DamageChallengeRule = (global::ReMastersLib.DamageChallengeThemeRule) input.ReadEnum();
            break;
          }
          case 24: {
            TrainerBaseId = input.ReadInt64();
            break;
          }
          case 32: {
            CyclicRankingQuestNum = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class DamageChallengeQuestSettingTable : pb::IMessage<DamageChallengeQuestSettingTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DamageChallengeQuestSettingTable> _parser = new pb::MessageParser<DamageChallengeQuestSettingTable>(() => new DamageChallengeQuestSettingTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DamageChallengeQuestSettingTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.DamageChallengeQuestSettingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DamageChallengeQuestSettingTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DamageChallengeQuestSettingTable(DamageChallengeQuestSettingTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DamageChallengeQuestSettingTable Clone() {
      return new DamageChallengeQuestSettingTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.DamageChallengeQuestSetting> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.DamageChallengeQuestSetting.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.DamageChallengeQuestSetting> entries_ = new pbc::RepeatedField<global::ReMastersLib.DamageChallengeQuestSetting>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.DamageChallengeQuestSetting> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DamageChallengeQuestSettingTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DamageChallengeQuestSettingTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DamageChallengeQuestSettingTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
