// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/MultipleParameterBoost.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/MultipleParameterBoost.proto</summary>
  public static partial class MultipleParameterBoostReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/MultipleParameterBoost.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MultipleParameterBoostReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJQcm90by9NdWx0aXBsZVBhcmFtZXRlckJvb3N0LnByb3RvEgxSZU1hc3Rl",
            "cnNMaWIi0gEKFk11bHRpcGxlUGFyYW1ldGVyQm9vc3QSIwobbXVsdGlwbGVf",
            "cGFyYW1ldGVyX2Jvb3N0X2lkGAEgASgEEhYKDmhwX2Jvb3N0X3JhdGlvGAIg",
            "ASgDEhcKD2F0a19ib29zdF9yYXRpbxgDIAEoAxIXCg9kZWZfYm9vc3RfcmF0",
            "aW8YBCABKAMSFwoPc3BhX2Jvb3N0X3JhdGlvGAUgASgDEhcKD3NwZF9ib29z",
            "dF9yYXRpbxgGIAEoAxIXCg9zcGVfYm9vc3RfcmF0aW8YByABKAMiVAobTXVs",
            "dGlwbGVQYXJhbWV0ZXJCb29zdFRhYmxlEjUKB2VudHJpZXMYASADKAsyJC5S",
            "ZU1hc3RlcnNMaWIuTXVsdGlwbGVQYXJhbWV0ZXJCb29zdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.MultipleParameterBoost), global::ReMastersLib.MultipleParameterBoost.Parser, new[]{ "MultipleParameterBoostId", "HpBoostRatio", "AtkBoostRatio", "DefBoostRatio", "SpaBoostRatio", "SpdBoostRatio", "SpeBoostRatio" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.MultipleParameterBoostTable), global::ReMastersLib.MultipleParameterBoostTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MultipleParameterBoost : pb::IMessage<MultipleParameterBoost>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MultipleParameterBoost> _parser = new pb::MessageParser<MultipleParameterBoost>(() => new MultipleParameterBoost());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MultipleParameterBoost> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.MultipleParameterBoostReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleParameterBoost() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleParameterBoost(MultipleParameterBoost other) : this() {
      multipleParameterBoostId_ = other.multipleParameterBoostId_;
      hpBoostRatio_ = other.hpBoostRatio_;
      atkBoostRatio_ = other.atkBoostRatio_;
      defBoostRatio_ = other.defBoostRatio_;
      spaBoostRatio_ = other.spaBoostRatio_;
      spdBoostRatio_ = other.spdBoostRatio_;
      speBoostRatio_ = other.speBoostRatio_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleParameterBoost Clone() {
      return new MultipleParameterBoost(this);
    }

    /// <summary>Field number for the "multiple_parameter_boost_id" field.</summary>
    public const int MultipleParameterBoostIdFieldNumber = 1;
    private ulong multipleParameterBoostId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong MultipleParameterBoostId {
      get { return multipleParameterBoostId_; }
      set {
        multipleParameterBoostId_ = value;
      }
    }

    /// <summary>Field number for the "hp_boost_ratio" field.</summary>
    public const int HpBoostRatioFieldNumber = 2;
    private long hpBoostRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long HpBoostRatio {
      get { return hpBoostRatio_; }
      set {
        hpBoostRatio_ = value;
      }
    }

    /// <summary>Field number for the "atk_boost_ratio" field.</summary>
    public const int AtkBoostRatioFieldNumber = 3;
    private long atkBoostRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long AtkBoostRatio {
      get { return atkBoostRatio_; }
      set {
        atkBoostRatio_ = value;
      }
    }

    /// <summary>Field number for the "def_boost_ratio" field.</summary>
    public const int DefBoostRatioFieldNumber = 4;
    private long defBoostRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long DefBoostRatio {
      get { return defBoostRatio_; }
      set {
        defBoostRatio_ = value;
      }
    }

    /// <summary>Field number for the "spa_boost_ratio" field.</summary>
    public const int SpaBoostRatioFieldNumber = 5;
    private long spaBoostRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SpaBoostRatio {
      get { return spaBoostRatio_; }
      set {
        spaBoostRatio_ = value;
      }
    }

    /// <summary>Field number for the "spd_boost_ratio" field.</summary>
    public const int SpdBoostRatioFieldNumber = 6;
    private long spdBoostRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SpdBoostRatio {
      get { return spdBoostRatio_; }
      set {
        spdBoostRatio_ = value;
      }
    }

    /// <summary>Field number for the "spe_boost_ratio" field.</summary>
    public const int SpeBoostRatioFieldNumber = 7;
    private long speBoostRatio_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long SpeBoostRatio {
      get { return speBoostRatio_; }
      set {
        speBoostRatio_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MultipleParameterBoost);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MultipleParameterBoost other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MultipleParameterBoostId != other.MultipleParameterBoostId) return false;
      if (HpBoostRatio != other.HpBoostRatio) return false;
      if (AtkBoostRatio != other.AtkBoostRatio) return false;
      if (DefBoostRatio != other.DefBoostRatio) return false;
      if (SpaBoostRatio != other.SpaBoostRatio) return false;
      if (SpdBoostRatio != other.SpdBoostRatio) return false;
      if (SpeBoostRatio != other.SpeBoostRatio) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MultipleParameterBoostId != 0UL) hash ^= MultipleParameterBoostId.GetHashCode();
      if (HpBoostRatio != 0L) hash ^= HpBoostRatio.GetHashCode();
      if (AtkBoostRatio != 0L) hash ^= AtkBoostRatio.GetHashCode();
      if (DefBoostRatio != 0L) hash ^= DefBoostRatio.GetHashCode();
      if (SpaBoostRatio != 0L) hash ^= SpaBoostRatio.GetHashCode();
      if (SpdBoostRatio != 0L) hash ^= SpdBoostRatio.GetHashCode();
      if (SpeBoostRatio != 0L) hash ^= SpeBoostRatio.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MultipleParameterBoostId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MultipleParameterBoostId);
      }
      if (HpBoostRatio != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(HpBoostRatio);
      }
      if (AtkBoostRatio != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AtkBoostRatio);
      }
      if (DefBoostRatio != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(DefBoostRatio);
      }
      if (SpaBoostRatio != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(SpaBoostRatio);
      }
      if (SpdBoostRatio != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SpdBoostRatio);
      }
      if (SpeBoostRatio != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(SpeBoostRatio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MultipleParameterBoostId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(MultipleParameterBoostId);
      }
      if (HpBoostRatio != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(HpBoostRatio);
      }
      if (AtkBoostRatio != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(AtkBoostRatio);
      }
      if (DefBoostRatio != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(DefBoostRatio);
      }
      if (SpaBoostRatio != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(SpaBoostRatio);
      }
      if (SpdBoostRatio != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(SpdBoostRatio);
      }
      if (SpeBoostRatio != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(SpeBoostRatio);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MultipleParameterBoostId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MultipleParameterBoostId);
      }
      if (HpBoostRatio != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(HpBoostRatio);
      }
      if (AtkBoostRatio != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AtkBoostRatio);
      }
      if (DefBoostRatio != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(DefBoostRatio);
      }
      if (SpaBoostRatio != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SpaBoostRatio);
      }
      if (SpdBoostRatio != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SpdBoostRatio);
      }
      if (SpeBoostRatio != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SpeBoostRatio);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MultipleParameterBoost other) {
      if (other == null) {
        return;
      }
      if (other.MultipleParameterBoostId != 0UL) {
        MultipleParameterBoostId = other.MultipleParameterBoostId;
      }
      if (other.HpBoostRatio != 0L) {
        HpBoostRatio = other.HpBoostRatio;
      }
      if (other.AtkBoostRatio != 0L) {
        AtkBoostRatio = other.AtkBoostRatio;
      }
      if (other.DefBoostRatio != 0L) {
        DefBoostRatio = other.DefBoostRatio;
      }
      if (other.SpaBoostRatio != 0L) {
        SpaBoostRatio = other.SpaBoostRatio;
      }
      if (other.SpdBoostRatio != 0L) {
        SpdBoostRatio = other.SpdBoostRatio;
      }
      if (other.SpeBoostRatio != 0L) {
        SpeBoostRatio = other.SpeBoostRatio;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MultipleParameterBoostId = input.ReadUInt64();
            break;
          }
          case 16: {
            HpBoostRatio = input.ReadInt64();
            break;
          }
          case 24: {
            AtkBoostRatio = input.ReadInt64();
            break;
          }
          case 32: {
            DefBoostRatio = input.ReadInt64();
            break;
          }
          case 40: {
            SpaBoostRatio = input.ReadInt64();
            break;
          }
          case 48: {
            SpdBoostRatio = input.ReadInt64();
            break;
          }
          case 56: {
            SpeBoostRatio = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MultipleParameterBoostId = input.ReadUInt64();
            break;
          }
          case 16: {
            HpBoostRatio = input.ReadInt64();
            break;
          }
          case 24: {
            AtkBoostRatio = input.ReadInt64();
            break;
          }
          case 32: {
            DefBoostRatio = input.ReadInt64();
            break;
          }
          case 40: {
            SpaBoostRatio = input.ReadInt64();
            break;
          }
          case 48: {
            SpdBoostRatio = input.ReadInt64();
            break;
          }
          case 56: {
            SpeBoostRatio = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MultipleParameterBoostTable : pb::IMessage<MultipleParameterBoostTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MultipleParameterBoostTable> _parser = new pb::MessageParser<MultipleParameterBoostTable>(() => new MultipleParameterBoostTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MultipleParameterBoostTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.MultipleParameterBoostReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleParameterBoostTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleParameterBoostTable(MultipleParameterBoostTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MultipleParameterBoostTable Clone() {
      return new MultipleParameterBoostTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.MultipleParameterBoost> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.MultipleParameterBoost.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.MultipleParameterBoost> entries_ = new pbc::RepeatedField<global::ReMastersLib.MultipleParameterBoost>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.MultipleParameterBoost> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MultipleParameterBoostTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MultipleParameterBoostTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MultipleParameterBoostTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
